### ISSUE TITLE
User Story 1: List of all Art Pieces

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#1]
#### Value Proposition

**As an** art enthusiast

**I want to** see a list of all art pieces

**so that** I can get an overview of all art pieces.

#### Acceptance Criteria

- [x] All art pieces are displayed as a list 🖼️
- [x] Each art piece's image is displayed 🖼️
- [x] Each art piece's title is displayed 🖼️
- [x] Each art piece's artist is displayed 🖼️

#### Tasks

- [x] Fetch all art pieces with `SWR` in `pages/index.js`
- [x] Create the component `ArtPieces` to render a list
- [x] `ArtPieces` props: `pieces`
- [x] Create the component `ArtPiecePreview`
- [x] `ArtPiecePreview` props: `image`, `title`, `artist`
- [x] All acceptance criteria marked with 🖼️ are covered by component testing

---
