### ISSUE TITLE
User Story 2: Spotlight Piece

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#2]
#### Value Proposition

**As an** art enthusiast

**I want to** see a spotlight piece

**so that** I can get inspirational highlights.

#### Acceptance Criteria

- [x] One art piece is picked at random to show as a spotlight piece
- [x] The art piece image is displayed 🖼️
- [x] The art piece artist is displayed 🖼️

#### Tasks

- [x] Write function to pick one art piece [at random](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random#examples)
- [x] Create the component `Spotlight`
- [x] `Spotlight` props: `image`, `artist`
- [x] All acceptance criteria marked with 🖼️ are covered by component testing

---
