### ISSUE TITLE
User Story 3: Separate Pages and Navigation Bar

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#3]
#### Value Proposition

**As an** art enthusiast

**I want to** be able to switch between the spotlight and list view

**so that** I can navigate the app easier.

#### Acceptance Criteria

- [x] A navigation link labeled "Spotlight" is displayed 🖼️
- [x] A navigation link labeled "Pieces" is displayed 🖼️
- [x] Clicking "Spotlight" shows the SpotlightPage
- [x] Clicking "Pieces" shows the ArtPiecesPage

#### Tasks

- [x] Move the data fetching logic to `pages/_app`
- [x] Find a solution for global state handling to have the art pieces available on all pages
- [x] Adapt the page `pages/index`: rename the function to `SpotlightPage` and have it render only the `Spotlight` component
- [x] Create the page `pages/art-pieces/index` that renders the `ArtPieces` component
- [x] Create the component `Navigation` that renders all navigation links
- [x] Create the component `Layout` that renders the `Navigation` component
- [x] Apply the `Layout` component in `pages/_app`
- [x] All acceptance criteria marked with 🖼️ are covered by component testing

---
