### ISSUE TITLE
User Story 4: Art Piece Details Page

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#4]
#### Value Proposition

**As an** art enthusiast

**I want to** be able to see the full art piece with detail information

**so that** I can learn everything about the piece.

#### Acceptance Criteria

- [x] Clicking an art piece from the list shows the detail page
- [x] The art piece image is displayed 🖼️
- [x] The art piece title is displayed 🖼️
- [x] The art piece artist is displayed 🖼️
- [x] The art piece year is displayed 🖼️
- [x] The art piece genre is displayed 🖼️
- [x] A back-button is displayed 🖼️
- [x] Clicking the back-button shows the list view

#### Tasks

- [x] Create the component `ArtPieceDetails`
- [x] `ArtPieceDetails` props: `image`, `title`, `artist`, `year`, `genre`
- [x] Create the page `pages/art-pieces/[slug]` that renders `ArtPieceDetails`
- [x] Read the query parameter `slug` from `next/router`
- [x] Use the `slug` to find the art piece to display
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

---
