### ISSUE TITLE
User Story 5: Favorites

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#5]
#### Value Proposition

**As an** art enthusiast

**I want to** mark art piece pieces as favorites

**so that** I can find them easier.

#### Acceptance Criteria

- [x] The favorite-button is displayed in the spotlight view 🖼️
- [x] The favorite-button is displayed in each entry in the list view 🖼️
- [x] The favorite-button is displayed in the details view 🖼️
- [x] Clicking the favorite-button on a non-favorite piece saves it as a favorite 🖼️
- [x] Clicking the favorite-button on a favorite piece removes it from favorites 🖼️

#### Tasks

- [x] Create an additional state `artPiecesInfo` to save further information for art pieces
- [x] Make the `artPiecesInfo` state globally available for all pages
- [x] Store the favorite flag in the `artPiecesInfo`
- [x] Reference art pieces by `slug` in the additional state
- [x] Create the component `FavoriteButton`
- [x] `FavoriteButton` props: `isFavorite`, `onToggleFavorite`
- [x] Render the `FavoriteButton` component in the `Spotlight`, `ArtPiecePreview` and `ArtPieceDetails` component
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

---
