### ISSUE TITLE
User Story 6: Favorite Listing Page

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#6]
#### Value Proposition

**As an** art enthusiast

**I want to** see a comprehensive list of all my favorite art pieces

**so that** I can have an overview of all of my favorites.

#### Acceptance Criteria

- [x] A navigation link labeled "Favorites" is displayed 🖼️
- [x] Clicking the "Favorites" shows the FavoritesPage
- [x] All favorite art pieces are displayed as a list 🖼️
- [x] Each art piece's image is displayed 🖼️
- [x] Each art piece's title is displayed 🖼️
- [x] Each art piece's artist is displayed 🖼️
- [x] Each art piece's is displayed with active favorite-button 🖼️

#### Tasks

- [x] Create the page `pages/favorites` that renders the `ArtPieces` component
- [x] Use data from the `artPiecesInfo` state to filter for all favorite art pieces
- [x] Pass the list of all favorite art pieces via prop `pieces` to the `ArtPieces` component
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

---
