### ISSUE TITLE
User Story 9: Show Color Palette

### ISSUE THREAD

**Issue by PacoSchwab** [PacoSchwab/art-gallery-app#9]
#### Value Proposition

**As an** art enthusiast

**I want to** see the color palette of an art piece

**so that** I can find color inspiration.

#### Acceptance Criteria

- [ ] The art piece detail page shows a list of all colors used in the image
- [ ] The colors may be displayed as circles, squares, ...

#### Tasks

- [ ] Pass the `colors` given by the API to the `ArtPieceDetails` component 🖼️
- [ ] Use the color hex-code in a styled component to render an element with this color as background
- [ ] All acceptance criteria marked with 🖼️ are covered by component testing

---
